server:
  port: 8081
  forward-headers-strategy: native

spring:
  application:
    name: api-gateway
  cloud:
    discovery.client.simple:
      instances:
        server-service:
          - uri: http://localhost:8082
        floating-ip-service:
          - uri: http://localhost:8083
        storage-service:
          - uri: http://localhost:8084
        identity-service:
          - uri: http://localhost:8085
    gateway.server.webflux:
      routes:
        - id: server-service
          uri: lb://server-service
          predicates:
            - Path=/servers/**
        - id: server-service-apm
          uri: lb://server-service
          predicates:
            - Path=/server-apm/**
        - id: floating-ip-service
          uri: lb://floating-ip-service
          predicates:
            - Path=/floating-ips/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storages/**
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/signin
            - Path=/signup
            - Path=/users/**
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, httpexchanges, busrefresh, info, metrics, prometheus
