server:
  port: 8082
spring:
  grpc:
    server:
      port: 50082
      servlet:
        enabled: false
  docker:
    compose:
      lifecycle-management: start_only
      start:
        skip: if_running
      file: compose.yaml

  jpa:
    database: mysql
    generate-ddl: true
