services:
  lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    container_name: lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - lgtm-grafana:/data/grafana
      - lgtm-prometheus:/data/prometheus
      - lgtm-loki:/data/loki
      - ./otel-collector-config.yml:/etc/otel-collector-config.yaml
    environment:
      - GF_PATHS_DATA=/data/grafana
      - OTEL_COLLECTOR_CONFIG=/etc/otel-collector-config.yaml

volumes:
  lgtm-grafana:
  lgtm-prometheus:
  lgtm-loki:
